-- ==============================================================
-- ข้อมูลอ้างอิงจริง (สาขา/พนักงาน/วัตถุดิบ/ระดับ par/รอบส่งของ)
-- ดึงตรงจากค่าคงที่ในต้นแบบ nomicha.html (BRANCHES/RELIEF/STOCK_ITEMS/REAL_PAR/ROUNDS/COMPANY) ด้วยสคริปต์
-- ป้องกันการพิมพ์ตัวเลขผิดมือ — รันต่อจาก schema.sql
-- ==============================================================

-- ที่อยู่จดทะเบียน — เจ้าของแจ้งมาเอง (5 ก.ย. 69) ทั้ง 2 บริษัทใช้ที่อยู่เดียวกัน
-- เลขผู้เสียภาษี 13 หลักของทั้ง 2 บริษัท เจ้าของยืนยันแล้ว 6 ก.ย. 69 (ดูข้อ 31 ในสเปก)
-- เจ้าของตรวจ/แก้ได้เองที่ หน้าเจ้าของ → ตั้งค่า → การ์ด "ข้อมูลบริษัท (สำหรับเอกสาร)"
update companies set address='เลขที่ 379/20 หมู่ที่ 13 ตำบลหนองเรือ อำเภอหนองเรือ จังหวัดขอนแก่น 40210', tax_id='0405567000967', vat_registered=false where id='warehouse';
update companies set address='เลขที่ 379/20 หมู่ที่ 13 ตำบลหนองเรือ อำเภอหนองเรือ จังหวัดขอนแก่น 40210', tax_id='0405567002137', vat_registered=false where id='branch_co';

-- สาขา (5 สาขาที่ยังเปิดอยู่ — บ้านแพงปิดแล้วไม่รวมในนี้)
-- เวลาทำงาน (work_start/work_end/late_grace_min) ใช้ค่าเริ่มต้น 08:00-18:00 ไม่ผ่อนผัน — เจ้าของตั้งค่าจริงได้ในหน้าตั้งค่า
insert into branches (id,name,float_cash,days_off_quota,holiday_work_days,gps_lat,gps_lng,gps_radius) values ('lnd','เหล่านาดี',300,2,1,16.411445,102.811,100);
insert into branches (id,name,float_cash,days_off_quota,holiday_work_days,gps_lat,gps_lng,gps_radius) values ('bwa','บ้านหว้า',300,4,0,16.384157,102.706986,100);
insert into branches (id,name,float_cash,days_off_quota,holiday_work_days,gps_lat,gps_lng,gps_radius) values ('nlb','หนองหลุบ',300,2,2,16.470103,102.755351,100);
insert into branches (id,name,float_cash,days_off_quota,holiday_work_days,gps_lat,gps_lng,gps_radius) values ('ksk','เขาสวนกวาง',500,2,0,16.85116,102.872658,100);
insert into branches (id,name,float_cash,days_off_quota,holiday_work_days,gps_lat,gps_lng,gps_radius) values ('bdt','บัณฑิต',300,2,1,16.434312,102.860083,100);

-- ค่าเช่าสาขา (ประวัติ — เท่ากันทุกสาขาตอนนี้ 5,055.75 บาท/เดือน)
insert into branch_rent_history (branch_id, effective_from, rent) values ('lnd','2026-01-01',5055.75);
insert into branch_rent_history (branch_id, effective_from, rent) values ('bwa','2026-01-01',5055.75);
insert into branch_rent_history (branch_id, effective_from, rent) values ('nlb','2026-01-01',5055.75);
insert into branch_rent_history (branch_id, effective_from, rent) values ('ksk','2026-01-01',5055.75);
insert into branch_rent_history (branch_id, effective_from, rent) values ('bdt','2026-01-01',5055.75);

-- ค่าเช่าคลังกลาง (จ่ายให้หัวหน้า)
insert into warehouse_rent_history (effective_from, rent) values ('2026-01-01',1000);

-- รอบส่งของ
insert into delivery_rounds (id,name,day_of_week,branch_ids) values ('r1','รอบจันทร์',1,'{"lnd","bwa","nlb","bdt"}');
insert into delivery_rounds (id,name,day_of_week,branch_ids) values ('r2','รอบศุกร์',5,'{"lnd","bwa","nlb","bdt","ksk"}');

-- หมวดวัตถุดิบ 8 หมวด
insert into stock_categories (id,name,sort_order) values (0,'บรรจุภัณฑ์',0);
insert into stock_categories (id,name,sort_order) values (1,'นม',1);
insert into stock_categories (id,name,sort_order) values (2,'ใบชา',2);
insert into stock_categories (id,name,sort_order) values (3,'ไข่มุก/วุ้น (ท็อปปิ้ง)',3);
insert into stock_categories (id,name,sort_order) values (4,'ผงชง/ครีม/น้ำตาล',4);
insert into stock_categories (id,name,sort_order) values (5,'น้ำเชื่อม/น้ำหวาน',5);
insert into stock_categories (id,name,sort_order) values (6,'โซดา',6);
insert into stock_categories (id,name,sort_order) values (7,'อื่น ๆ',7);

-- วัตถุดิบ 45 รายการ (id ตรงกับต้นแบบเป๊ะ ตั้งแต่ 0-44)
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (0,'แก้วเย็น','แถว',2,20,65,0,0);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (1,'แก้วปั่น','แถว',1,20,88,0,1);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (2,'ฝาโดม','แถว',2,20,35,0,2);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (3,'นมสด','กล่อง',3,12,50,1,7);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (4,'คาร์เนชั่น นมจืด','กระป๋อง',4,48,26,1,8);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (5,'คาร์เนชั่น นมข้นหวาน','ถุง',1,8,117,1,9);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (6,'ผงครีมเทียม','ถุง',1,12,72,4,21);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (7,'น้ำตาล','ถุง',2,25,29,4,22);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (8,'น้ำเชื่อม','ถุง',2,8,86,5,31);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (9,'ชาเขียว','ห่อ',1,40,160,2,11);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (10,'ชาแดง','ห่อ',1,40,160,2,12);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (11,'ชาไต้หวัน','ห่อ',1,40,180,2,13);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (12,'ไข่มุกดำ','ห่อ',3,18,35,3,17);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (13,'วุ้นบราวชูการ์','ถุง',1,20,43,3,18);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (14,'วุ้นเยลลี่ผลไม้','ถุง',1,20,36,3,19);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (15,'วุ้นคริสตัล','ถุง',1,20,39,3,20);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (16,'หลอดเล็ก','ห่อ',2,50,20,0,3);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (17,'หลอดใหญ่','ห่อ',2,20,20,0,4);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (18,'ผงโกโก้','ห่อ',1,12,190,4,23);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (19,'น้ำบราวชูการ์','ขวด',1,12,75,5,33);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (20,'น้ำแดง','ขวด',1,12,67,5,34);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (21,'น้ำผึ้ง','ขวด',1,12,100,5,32);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (22,'ถุงเดี่ยว','ถุง',1,150,20,0,5);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (23,'ถุงคู่','ถุง',1,60,50,0,6);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (24,'ชาพีช','ห่อ',1,40,180,2,14);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (25,'ชากุหลาบ','ห่อ',1,40,180,2,15);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (26,'ชามะลิ','ห่อ',1,40,180,2,16);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (27,'กาแฟโบราณ','ถุง',1,6,94,4,24);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (28,'กาแฟบอน','ขวด',1,12,120,4,25);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (29,'กาแฟเนส','ถุง',1,12,385,4,26);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (30,'ผงโอวัลติน','ถุง',1,12,158,4,27);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (31,'ผงเผือก','ถุง',1,12,142,4,28);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (32,'ผงมะนาว','ถุง',1,15,85,4,29);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (33,'น้ำสตรอเบอรี่','ขวด',1,12,75,5,35);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (34,'น้ำแคนตาลูป','ขวด',1,12,75,5,36);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (35,'น้ำลิ้นจี่','ขวด',1,12,75,5,37);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (36,'น้ำบลูฮาวาย','ขวด',1,12,75,5,38);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (37,'น้ำแอปเปิ้ล','ขวด',1,12,75,5,39);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (38,'น้ำวนิลา','ขวด',1,12,142,5,40);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (39,'น้ำคาราเมล','ขวด',1,12,142,5,41);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (40,'น้ำมะพร้าว','ขวด',1,6,190,5,42);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (41,'โซดาร๊อค','ขวด',1,24,6.46,6,43);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (42,'ผงแคนตาลูป','ถุง',1,12,142,4,30);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (43,'นมหมี','กระป๋อง',6,12,135,1,10);
insert into stock_items (id,name,unit,min_qty,per_case,branch_price,category_id,display_order) values (44,'น้ำยาล้างจาน','ถุง',1,1,10,7,44);

-- ระดับที่ต้องมีต่อรอบ แยกรายสาขา (ข้อมูลจริงที่เจ้าของกรอกมา 45 รายการ x 5 สาขา)
insert into stock_par_levels (item_id, branch_id, par_qty) values (0, 'lnd', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (0, 'bwa', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (0, 'nlb', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (0, 'ksk', 12);
insert into stock_par_levels (item_id, branch_id, par_qty) values (0, 'bdt', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (1, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (1, 'bwa', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (1, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (1, 'ksk', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (1, 'bdt', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (2, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (2, 'bwa', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (2, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (2, 'ksk', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (2, 'bdt', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (3, 'lnd', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (3, 'bwa', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (3, 'nlb', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (3, 'ksk', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (3, 'bdt', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (4, 'lnd', 25);
insert into stock_par_levels (item_id, branch_id, par_qty) values (4, 'bwa', 30);
insert into stock_par_levels (item_id, branch_id, par_qty) values (4, 'nlb', 25);
insert into stock_par_levels (item_id, branch_id, par_qty) values (4, 'ksk', 50);
insert into stock_par_levels (item_id, branch_id, par_qty) values (4, 'bdt', 25);
insert into stock_par_levels (item_id, branch_id, par_qty) values (5, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (5, 'bwa', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (5, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (5, 'ksk', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (5, 'bdt', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (6, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (6, 'bwa', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (6, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (6, 'ksk', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (6, 'bdt', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (7, 'lnd', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (7, 'bwa', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (7, 'nlb', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (7, 'ksk', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (7, 'bdt', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (8, 'lnd', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (8, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (8, 'nlb', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (8, 'ksk', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (8, 'bdt', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (9, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (9, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (9, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (9, 'ksk', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (9, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (10, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (10, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (10, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (10, 'ksk', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (10, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (11, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (11, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (11, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (11, 'ksk', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (11, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (12, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (12, 'bwa', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (12, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (12, 'ksk', 8);
insert into stock_par_levels (item_id, branch_id, par_qty) values (12, 'bdt', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (13, 'lnd', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (13, 'bwa', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (13, 'nlb', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (13, 'ksk', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (13, 'bdt', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (14, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (14, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (14, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (14, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (14, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (15, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (15, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (15, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (15, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (15, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (16, 'lnd', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (16, 'bwa', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (16, 'nlb', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (16, 'ksk', 4);
insert into stock_par_levels (item_id, branch_id, par_qty) values (16, 'bdt', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (17, 'lnd', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (17, 'bwa', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (17, 'nlb', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (17, 'ksk', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (17, 'bdt', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (18, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (18, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (18, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (18, 'ksk', 3);
insert into stock_par_levels (item_id, branch_id, par_qty) values (18, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (19, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (19, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (19, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (19, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (19, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (20, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (20, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (20, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (20, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (20, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (21, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (21, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (21, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (21, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (21, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (22, 'lnd', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (22, 'bwa', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (22, 'nlb', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (22, 'ksk', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (22, 'bdt', 5);
insert into stock_par_levels (item_id, branch_id, par_qty) values (23, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (23, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (23, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (23, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (23, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (24, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (24, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (24, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (24, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (24, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (25, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (25, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (25, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (25, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (25, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (26, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (26, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (26, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (26, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (26, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (27, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (27, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (27, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (27, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (27, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (28, 'lnd', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (28, 'bwa', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (28, 'nlb', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (28, 'ksk', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (28, 'bdt', 2);
insert into stock_par_levels (item_id, branch_id, par_qty) values (29, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (29, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (29, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (29, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (29, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (30, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (30, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (30, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (30, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (30, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (31, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (31, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (31, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (31, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (31, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (32, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (32, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (32, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (32, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (32, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (33, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (33, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (33, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (33, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (33, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (34, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (34, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (34, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (34, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (34, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (35, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (35, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (35, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (35, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (35, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (36, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (36, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (36, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (36, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (36, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (37, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (37, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (37, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (37, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (37, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (38, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (38, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (38, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (38, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (38, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (39, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (39, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (39, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (39, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (39, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (40, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (40, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (40, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (40, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (40, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (41, 'lnd', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (41, 'bwa', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (41, 'nlb', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (41, 'ksk', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (41, 'bdt', 10);
insert into stock_par_levels (item_id, branch_id, par_qty) values (42, 'lnd', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (42, 'bwa', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (42, 'nlb', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (42, 'ksk', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (42, 'bdt', 6);
insert into stock_par_levels (item_id, branch_id, par_qty) values (43, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (43, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (43, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (43, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (43, 'bdt', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (44, 'lnd', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (44, 'bwa', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (44, 'nlb', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (44, 'ksk', 1);
insert into stock_par_levels (item_id, branch_id, par_qty) values (44, 'bdt', 1);

-- คลังกลาง: เริ่มที่ 0 ทุกรายการตามหลักการระบบจริง (ข้อ 22.3) — เจ้าของนับสต๊อกจริงแล้วค่อย UPDATE/INSERT purchases เอง
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (0, 0, 0, 58.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (1, 0, 0, 79.20);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (2, 0, 0, 31.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (3, 0, 0, 45.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (4, 0, 0, 23.40);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (5, 0, 0, 105.30);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (6, 0, 0, 64.80);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (7, 0, 0, 26.10);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (8, 0, 0, 77.40);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (9, 0, 0, 144.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (10, 0, 0, 144.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (11, 0, 0, 162.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (12, 0, 0, 31.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (13, 0, 0, 38.70);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (14, 0, 0, 32.40);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (15, 0, 0, 35.10);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (16, 0, 0, 18.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (17, 0, 0, 18.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (18, 0, 0, 171.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (19, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (20, 0, 0, 60.30);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (21, 0, 0, 90.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (22, 0, 0, 18.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (23, 0, 0, 45.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (24, 0, 0, 162.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (25, 0, 0, 162.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (26, 0, 0, 162.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (27, 0, 0, 84.60);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (28, 0, 0, 108.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (29, 0, 0, 346.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (30, 0, 0, 142.20);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (31, 0, 0, 127.80);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (32, 0, 0, 76.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (33, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (34, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (35, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (36, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (37, 0, 0, 67.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (38, 0, 0, 127.80);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (39, 0, 0, 127.80);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (40, 0, 0, 171.00);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (41, 0, 0, 5.81);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (42, 0, 0, 127.80);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (43, 0, 0, 121.50);
insert into warehouse_stock (item_id, case_qty, loose_qty, avg_cost) values (44, 0, 0, 9.00);
-- avg_cost ตั้งต้น = ราคาส่งสาขา - 10% (สูตรทางการตามข้อ 21) จะขยับเองเมื่อมีบิลซื้อจริงเข้ามา (ดู purchases + ฟังก์ชันคำนวณฝั่งแอป)

-- พนักงาน 7 คน (staff x5 + หัวหน้า + เจ้าของ) ต้องสร้างผ่าน Supabase Auth ก่อน (Dashboard > Authentication > Add user)
-- แล้วค่อย insert ตารางนี้โดยใช้ uuid ของแต่ละคนจาก auth.users (ดูขั้นตอนใน docs/DEPLOY.md ข้อ 4)
